name: Maven version
author: Petr Portnov
description: Resolves Maven project version
branding:
  icon: search
  color: orange

inputs:
  pom:
    description: Path to Maven's pom.xml file
    required: false
  settings:
    description: Path to Maven's settings.xml file
    required: false
outputs:
  version:
    description: Resolved Maven version
    value: ${{ steps.resolve-version.outputs.resolved-version }}

runs:
  using: composite
  steps:
    - id: resolve-version
      shell: bash
      run: "echo \"::set-output name=resolved-version::\
        $(mvn
          ${{ inputs.pom != '' && format('--file={0}', inputs.pom) || '' }}
          ${{ inputs.settings != '' && format('--settings={0}', inputs.settings) || '' }}
          --quiet --non-recursive
          exec:exec -Dexec.executable=echo -Dexec.args='${project.version}'
        )\""
