name: Maven version
author: Petr Portov
description: Resolves Maven project version
branding:
  icon: search
  color: orange

inputs:
  pom:
    description: Path to Maven's pom.xml file
    required: true
    default: ./pom.xml
  settings:
    description: Path to Maven's settings.xml file
    required: false
outputs:
  version:
    description: Resolved Maven version
    value: ${{ steps.resolve-version.outputs.resolved-version }}

runs:
  using: composite
  steps:
    - id: prepare-settings
      shell: bash
      if: ${{ inputs.settings != '' }}
      run: echo "SETTINGS=--settings ${{inputs.settings}}" >> $GITHUB_ENV
    - id: resolve-version
      shell: bash
      run: "echo \"::set-output name=resolved-version::\
        $(mvn
          --file ${{ inputs.pom }}
          $SETTINGS
          -Dexec.executable=echo
          -Dexec.args='${project.version}'
          --non-recursive exec:exec --quiet
        )\""
